feed/history/boost_1_58_0.qbk

Dear @danieljames,
Please find the updated release notes for Boost 1.58.0 with Boost.Fusion changes as merged in boostorg/fusion#48 and boostorg/fusion#55.
These changelog were discussed with @Flast and @djowel in boostorg/fusion#55.
Cheers,

Boost.Fusion changelog for Boost 1.58.0

---

feed/history/boost_1_58_0.qbk

`BOOST_MOVE_BASE BOOST_MOVE_BASE`
to
`BOOST_MOVE_BASE`

[1.58.0] Move release note : remove duplicate identifier

---

feed/history/boost_1_58_0.qbk
patches/1_58_0/0002-Fix-a-regression-with-non-constexpr-types.patch
patches/index.html

Boost.Fusion has [a regression (#11211)](https://svn.boost.org/trac/boost/ticket/11211) in 1.58 release: this PR publish a patch to fix it, including https://github.com/boostorg/fusion/pull/70, https://github.com/boostorg/fusion/pull/71 and https://github.com/boostorg/fusion/pull/72.
CC: @djowel , @daminetreg

Patch for Fusion regression.

---

feed/history/boost_1_59_0.qbk

execution_context of boost.context switches its internal implementation to Windows Fibers wit hcompiler flag BOOST_USE_WINFIBERS

notice about support of Windows Fibers

---

feed/history/boost_1_59_0.qbk

Hi,
I am not sure about the procedure, I am proposing this PR to update the changelog of the boost.test v3 appearing in the next release of boost (1.59).
BTW, is there any automatic way of pointing to a .qbk in this file? I would like to know if I can point to the changelog of boost.test directly from the release page.
Thanks!

Updated change log for boost.test v3

---

feed/history/boost_1_60_0.qbk

I did as suggested on the [mailing list](http://article.gmane.org/gmane.comp.lib.boost.devel/263965), although I think it might be overkill to add a new section just for announcing Hana's postponed release. Maybe it would be better to add a one-liner at the bottom of the __New libraries__ section, which is where people would look first?

Add note about Hana's postponed release for 1.60.0

---

feed/history/boost_1_60_0.qbk

- Add release notes for Boost.Atomic, Boost.Core, Boost.Log and Boost.UUID.
- Add a release note for Windows users about the new default target Windows version.

Update release notes

---

feed/history/boost_1_60_0.qbk

I am not sure about the link `[@/doc/libs/1_60_0/libs/test/doc/html/...` for pointing to the changelog. I adapted the Spirit link for that. The final URL should be `http://www.boost.org/doc/libs/master/libs/test/doc/html/boost_test/change_log.html` .

Change log update for boost.test / boost 1.60

---

feed/history/boost_1_60_0.qbk

I believe those lines are describing about my runner which named `Flast-FreeBSD10-*` in regression matrix, and those runners always run under C++11 mode (it is configured via command line, see last section of [Flast-FreeBSD10-clang~gnu++11](http://www.boost.org/development/tests/develop/Flast-FreeBSD10-clang~gnu++11.html)).

Correct runner's standards.

---

feed/history/boost_1_61_0.qbk

9943 is MSM's ticket. Correct ticket number is 9443.
Related pull request is fllow:
<https://github.com/boostorg/test/pull/98>

[1.61.0 release note][test] fix ticket number

---

feed/history/boost_1_61_0.qbk

s/intersect/intersects/
s/disjoints/disjoint/
see reference document: <http://www.boost.org/doc/libs/1_61_0/libs/geometry/doc/html/geometry/matrix.html>

[1.61] fix typo geometry function names

---

feed/history/boost_1_62_0.qbk

s/tgamma_delta_ration/tgamma_delta_ratio/
And I add code qualify.
Related commit is https://github.com/boostorg/math/commit/3891523510a65c202169e168789254f2156f8e45

Fix function name for Boost.Math release note

---

feed/history/boost_1_63_0.qbk

It seems that the runtime_cast URL is incorrect (404), and I think this is the correct one (based on seeing how other doc URLs are specified in other qbk files). But I can't actually test it, so I'm not entirely sure that this is indeed the correct one.

Point runtime_cast docs at the correct url

---

feed/history/boost_1_64_0.qbk

see macro name `BOOST_INTERPROCESS_BOOTSTAMP_IS_SESSION_MANAGER_BASED` and related commit https://github.com/boostorg/interprocess/commit/eedc9b0a4efd428104c5c9ebb61c83704166448e

1.64.0 : fix typo s/booststamp/bootstamp/

---

feed/history/boost_1_66_0.qbk

Depends on submission of https://github.com/boostorg/uuid/pull/54 which makes the release note unnecessary.

remove unnecessary release note for uuid

---

community/review_schedule.html

* The `outcome` entry in the table had a couple of columns swapped
* The release date for Boost.1.66.0 was a year off (2018 instead of 2017)

Fix a couple of typos in the review schedule

---

feed/history/boost_1_67_0.qbk

Now doesn't link to the ticket.
http://www.boost.org/users/history/version_1_67_0.html

[1.67.0] fix Spirit ticket link

---

development/header.html

Spells out already established convention.

Add note on #include "furball.hpp" as discouraged

---

feed/history/boost_1_68_0.qbk

I assume you are going to alphabetize the release notes by repository before release?  They are not organized properly right now.

removed one entry for Boost.Rational

---

feed/history/boost_1_68_0.qbk

Per the discussion on the mailing list, Boost.Signals was deprecated in 1.54.0 and will be removed in 1.69.0.  Adding a release note in 1.68.0 to warn folks of the upcoming change.  All users can transition to Boost.Signals2 or fork the repository and manage it themselves.

removal notice for Boost.Signals (1)

---

users/license.html

This is based on conclusions following various discussions on the Boost
mailing list, which have been summarised in the thread
"Guidelines on copyright notice maintenance"
https://lists.boost.org/Archives/boost/2018/07/242396.php
/cc @pabristow

Add guidelines on how to maintain copyright messages

---

users/faq.html

This update is based on @jzmaddock -s helpful recommendations posted to the ML:
* https://lists.boost.org/Archives/boost/2018/08/243169.php
* https://lists.boost.org/Archives/boost/2018/08/243175.php
I believe, those are worth to present and preserved on the website.

Update FAQ on how can I contribute as member of CMT

---

feed/history/boost_1_68_0.qbk
feed/history/boost_1_69_0.qbk

LLVM Project's Clang and Apple Clang use different version numbering system. On OS X, tested compilers are Apple Clang but not (LLVM Project's) Clang.

Fix tested compiler names: Clang -> Apple Clang

---

community/error_handling.html
users/bibliography.html

The two links to the Springer website that this commit replaces are broken. The doi links point to the intended resource (if I didn't make a mistake) and are intended to resolve correctly even if the Springer website should change again (see https://www.doi.org/ ).

Replaces two broken to books with doi permalinks.

---

feed/history/boost_1_71_0.qbk
feed/templates/boost_x_xx_x.qbk

Added examples for github, github pull requests, links, bolding, unicode, etc.
This wasn't carried over from the 1_70_0 feed history.  Why?

Update the example for release notes

---

feed/history/boost_1_70_0.qbk
feed/history/boost_1_71_0.qbk

Hi,
This is the change log for Boost.Test. It contains also a little link fix for the release notes of 1.70, I do not know if those would be deployed/backported. If you want me to remove that fix, please let me know.

Boost.Test change log for 1.71

---

users/license.html

The link to Mr. Smith's site at nixonpeabody.com is dead since 2006, but there is still a copy at web.archive.org. While that provides more information than a 404 page, apparently the person does not work at Nixon Peabody anymore, so maybe removing the link entirely is also a sensible option.
The addresses of the people page for Diane Cabell and the Berkman Center for Internet & Society have also changed.

Replace dead link with web.archive.org-link

---

feed/history/boost_1_72_0.qbk

This updates notes added in #459 with changes that arrived to GIL `master` in post-beta merge following green light from @mjcaisse  in https://lists.boost.org/Archives/boost/2019/11/247433.php
/cc @stefanseefeld

Update GIL release notes for Boost 1.72.0

---

community/irc.html

There is no such channel on irc freenode.

Deleted information about #boost-soc on irc.

---

community/index.html

Remove broken link to Google+ community which is no longer existent (HTTP 404).

Remove broken link to Google+ community

---

common/menu-welcome.html
development/bugs.html
index.html

Points to Wiki at the new location https://github.com/boostorg/wiki/wiki
Fixes #471

Update Wiki link to point at GitHub Wiki

---

feed/history/boost_1_72_0.qbk

It's just refactoring of GIL release notes.
Apparently, I'm late catcher wrt the quickbook cool stuff :)

Replace URLs to GIL pull requests with github_pr template

---

feed/history/boost_1_73_0.qbk

The GIL `develop` branch has now been merged to `master` and includes all the changes listed here.

Add GIL release notes for Boost 1.73.0

---

feed/history/boost_1_73_0.qbk

Missing Markdown to Quickbook correction.

Fix link syntax in GIL release notes

---

development/requirements.html

The config top level directory in the library structure contains build-time configuration checks. This directory is already used in this way in a number of libraries, and more and more libraries wish to add new build-time checks. This commit provides a guideline where such check could be placed.

Add description of the config top level directory

---

common/code/boost_libraries.php
common/code/boost_utility.php
doc/libraries.php

- Remove 'Standard' field from each library info
- Remove 'Standard Proposals' and 'TR1 libraries' from sort categories
- Add 'C++ Minimum' to sort categories

Update library doc page with 'Standard' field removed

---

common/code/boost_libraries.php
common/code/boost_utility.php

- Added secondary sort by library's name on same cxxstd values When sorting by C++ Minimum
- Removed 'std' from XML parsing as it has been removed from the XML file by the latest build.

Add secondary sort by name to C++ Minimum (cxxstd)

---

common/code/test/composer.json
common/code/test/composer.lock

Travis tests are being run from the common/code/test/ folder.
It contains composer.json and composer.lock files.
Lock all composer packages to known working versions.

Lock mustache/spec to sha in composer.lock

---

feed/history/boost_1_76_0.qbk

Nothing new, just carrying over the important notice from the Boost 1.75.0 notes (#562).

Add GIL release notes for Boost 1.76.0

---

common/code/boost_site_tools.php

This changes to the current name of the build tool and, like the other tools, moves the link to the canonical "tools/build" location.

Adjust B2 name and link to "local" direct location.

---

feed/history/boost_1_76_0.qbk

Not sure if `s=` is some special fomatting.

Fix typo in 1.76.0 release notes

---

feed/history/boost_1_76_0.qbk

In case we're still in time to update the changelog for 1.76

1.76: Container, Intrusive, Interprocess, Move

---

feed/history/boost_1_78_0.qbk
patches/1_78_0/0001-b2-fix-install.patch
patches/index.html

In Boost 1.78.0, `b2 install` does not install Boost.Stacktrace binaries on Linux. Add a post-prelease note with a patch.
Related issue: https://github.com/bfgroup/b2/issues/104
Related PR: https://github.com/bfgroup/b2/pull/113

Add a post-release not and patch for Boost.Build fixing library installs

---

feed/history/boost_1_80_0.qbk

Adds release notes for GIL, based on the [current RELEASES.md on the master branch](https://github.com/boostorg/gil/blob/bd17dd49f3d9d06a031554de67c26669b319205d/RELEASES.md).
@mloskot:
Not sure whether I got the syntax and formatting completely right, because I am not familiar with the QuickBook format.

update release notes for GIL in Boost 1.80.0

---

feed/history/boost_1_80_0.qbk

s/construct_method/construct_matched/
https://github.com/boostorg/gil/pull/653

1.80.0 : fix typo of GIL function name

---

development/website_updating.html

The documentation for configuring the website had mentioned a requirement to have the "website branch of Boost.Build".   However, the website branch of Boost.Build does not exist.    If this should be modified in a different way, let me know.

Update website doc

---

common/code/boost_filter_basic.php
common/code/boost_filter_boost_book_basic.php
common/code/template.php
common/heading.html
doc/libraries.php

This removes the boost-gecko script from all previous locations and only adds it to the header, so it will be loaded on all pages.

Add boost-gecko script to heading

---

feed/history/boost_1_83_0.qbk

I haven't found a way to visualize how notes look like in localhost - please net me know if anything looks wrong, or a way to do it. Thanks.

Boost.MySQL 1.83 release notes

---

generated/download-items.html
generated/home-items.html
users/history/version_1_84_0.html

These webpages are in the "generated/" folder of the website.  We'll have to see if they can be manually updated or will be re-generated.

Host boost downloads on AWS Cloudfront

---

users/download/index.html

I've fixed the wiki link in the [downloads page](https://www.boost.org/users/download/), by inserting the GitHub wiki address. Also, I've added the link to the main github repository.

Fixed main repository link.

---

feed/history/boost_1_86_0.qbk

Some dependencies of boost::format dropped C++03 support.  Although boost::format had no deprecation period, the issue was forced.
I am not a fan of the per-library C++ level support and supported compilers.  It would be easier for consumers if we all agreed on this and all moved forward together.
This closes jeking3/format#96

Release note for boost::format requiring C++11 in 1.86.0

---

feed/history/boost_1_86_0.qbk

Adds the release notes for GIL in Boost 1.86.0, based on the [current RELEASES.md on GIL's master branch](https://github.com/boostorg/gil/blob/201f31c76eed54b304f8d89e44da08a5e8825094/RELEASES.md).
/cc @mloskot

Add release notes for GIL in Boost 1.86.0

---

community/policy.html

Apparently, the self-closed `<a name"email-footers"/>` tag is not allowed and breaks rendering of the section body in Firefox 128. Convert it to an open+close pair.

Fix rendering of the section regarding email footers

---

common/code/boost_site_tools.php
community/groups.html
doc/tools.html
generated/menu-doc.html

The main redirect page is tools/boostbook/index.html, so point all links to that page. It will then redirect to the actual place where the built BoostBook documentation is (which is currently tools/boostbook/doc/html).
Refs https://github.com/boostorg/boostbook/issues/29.

Update links to BoostBook documentation

---

feed/history/boost_1_87_0.qbk

Add release notes for: Charconv, test, math, and multiprecision. Fixes the ordering of PFR.
CC: @jzmaddock, @ckormanyos, @NAThompson

Add release notes for: Charconv, test, math, and multiprecision 
