feed/history/boost_1_58_0.qbk

Release notes for version 1.58 for those libraries

1.58 Container, Interprocess, Intrusive & Move

---

feed/history/boost_1_59_0.qbk

Hi @djowel , @K-ballo and @daminetreg !
Here is 1.59.0 release notes for Fusion. Could you review this?

Release notes for Fusion.

---

feed/history/boost_1_59_0.qbk

I hope we are still on time ;-)

Container, Interprocess, Intrusive & Move release notes

---

feed/history/boost_1_59_0.qbk

Hi @djowel and release manager,
I update 1.59.0 release notes for post beta bugfixes.
Could you review this?

Post beta bugfixes for Fusion.

---

feed/history/boost_1_60_0.qbk

The versions are 12.4(C++version 5.13) and 12.5(C++version 5.14).

Sun compilers are now Oracle Solaris Studio.

---

feed/history/boost_1_60_0.qbk

@djowel , could you check this notes?

Add release notes for Fusion.

---

feed/history/boost_1_60_0.qbk

Changelog for Container, Interprocess, Intrusive and Move

Container, Interprocess, Intrusive & Move

---

feed/history/boost_1_60_0.qbk

added odeint release notes

---

community/official_library_maintainer_program.html

To follow the discussion and see Rob's suggestion, here's the link.
https://groups.google.com/forum/#!topic/boost-steering/OFmB6D0P6JI

Made changes suggested by Rob Stewart.

---

feed/history/boost_1_61_0.qbk

Added 1.61.0 release notes for Fusion.

---

feed/history/boost_1_61_0.qbk

Please merge the change log to the website. Thanks!

boost.test 1.61 change log update

---

feed/history/boost_1_61_0.qbk

test release notes insert before variant.

[1.61.0 release note] fix alphabetical order

---

development/reuse.html
development/testing.html

I found these unmerged commits while trying to clean up my portfolio.  It looks like I simply forgot to make a PR back then, so now I catch up on it.

Fix typos and a dead link

---

feed/history/boost_1_61_0.qbk

@djowel chould you check this?

Post beta fusion updates.

---

feed/history/boost_1_62_0.qbk

Added release notes for Phoenix.

---

feed/history/boost_1_62_0.qbk

1.62 Boost.Test change log

---

feed/history/boost_1_62_0.qbk

Updated change log of Boost.test. 
PS: my editor is removing the trailing spaces. Let me know if this is a problem for the PR.

Boost.test updated change log

---

feed/history/boost_1_63_0.qbk

Fix link to runtime_cast docs.

---

feed/history/boost_1_63_0.qbk

Added release notes for Fusion and Phoenix.

---

feed/history/boost_1_63_0.qbk

Boost.test @ 1.63 release notes

---

users/people/aleksey_gurtovoy.html

Updated my bio, please merge when you get a chance.

Update Gurtovoy's bio

---

feed/history/boost_1_64_0.qbk

Boost.test @ 1.64 release notes

---

development/submissions.html

Many thanks to @camio for these edits to make the page more friendly.

David Sankel's copy editing of the submissions page

---

users/index.html

Existing link reads to entirely wrong website for Scott Meyers' book, updated to provide proper link

Update broken link

---

feed/history/boost_1_65_0.qbk

Boost.test 1.65 change log

---

feed/history/boost_1_65_0.qbk

Important regression of Boost.Tread on windows. Patch available.

Important regression of Boost.Thread on windows in boost-1.65

---

feed/history/boost_1_66_0.qbk

Add preliminary release notes for Atomic, DateTime, Iterator, Log and Utility.

Add preliminary release notes

---

feed/history/boost_1_66_0.qbk

sneaking one more fix in under the wire...

add format volatile note

---

feed/history/boost_1_66_0.qbk

Added fusion release notes

---

feed/history/boost_1_67_0.qbk

Change log for boost.test 1.67

---

feed/history/boost_1_67_0.qbk

Release note for Fusion and Phoenix

---

feed/history/boost_1_67_0.qbk

Trac 245
https://svn.boost.org/trac10/ticket/245
GitHub 245
https://github.com/boostorg/spirit/pull/245

[1.67.0] fix URL of Spirit issue

---

community/generic_programming.html

Replace broken SGI links with cppreference

---

community/review_schedule.html

Related to GIL release notes in #342 
-----
I'm pleased to announce that after long years following [review and acceptance](https://lists.boost.org/boost-announce/2011/01/0281.php), @chhenning efforts reimplementing GIL I/O are now being released.
Thanks to @stefanseefeld for final refactoring and restructuring of the I/O extension.

Update review schedule about GIL IO released in 1.68

---

feed/history/boost_1_68_0.qbk

just what the subject implies...

Add release notes for GIL and Python.

---

development/requirements.html

This reflects the conclusion we seemed to have reached on the mailing list in this discussion: https://lists.boost.org/Archives/boost/2017/12/240071.php

Add notes on backwards compatibility

---

feed/history/boost_1_68_0.qbk

Added release notes for fusion

---

feed/history/boost_1_68_0.qbk

Sorry for the late PR (change of city+work etc...)

Boost1.68: Boost.test change log

---

feed/history/boost_1_68_0.qbk
feed/history/boost_1_69_0.qbk

Added a comment to avoid other confusion between GH issues and PRs
Fixed boost 1.68 PRs links for Boost.test

Boost.test change log for 1.69

---

feed/history/boost_1_68_0.qbk

Fixed a typo

---

feed/history/boost_1_70_0.qbk

Change log for Boost.Test / 1.70

---

feed/history/boost_1_70_0.qbk

Fixes a broken link and simplifies some style

Update beast release notes

---

feed/history/boost_1_71_0.qbk

This documents a breaking change in uuid that will not affect the vast majority of users.

Update for uuid 1.71

---

feed/history/boost_1_71_0.qbk

Container, Move, Interprocess, Intrusive

---

feed/history/boost_1_71_0.qbk

Add Beast release notes

---

feed/history/boost_1_72_0.qbk

Copied and converted to Quickbook from https://github.com/boostorg/gil/blob/develop/RELEASES.md
/cc @stefanseefeld @miralshah365 @simmplecoder

Add release notes for GIL

---

feed/history/boost_1_72_0.qbk

Change log 1.72 boost.test

---

community/gsoc.html

This is based on the instructions from previous years, still available on the old Wiki:
- https://svn.boost.org/trac10/wiki/SoC2015
- https://svn.boost.org/trac10/wiki/SoC2014
and it should address student's requests posted to the mailing lists:
- https://lists.boost.org/Archives/boost/2020/01/248136.php

Update gsoc.html with instructions how to submit competency test

---

community/gsoc.html

Tidy up and sort links in chronological order
/cc @yimyom

Complete list of past GSoC project ideas

---

index.html

Minor spelling error : Change reply to rely on front page.

Correct minor spelling mistake on front page.

---

feed/history/boost_1_73_0.qbk

Could you check the fix @apolukhin ?
33 is nothing.

1.73.0 fix lexical cast link

---

community/review_schedule.html

Add Nowide release to review results table

---

community/gsoc.html

Added the list of GSoC 2020 projects and refreshed a bit this old page.

Added GSoC 2020 projects, improved text and fixed links

---

feed/history/boost_1_74_0.qbk

I included the heap moving as it will otherwise conflict

Add nowide changelog and move heap to correct place

---

feed/history/boost_1_74_0.qbk

Add code formatting for keywords and other names

---

common/code/boost_libraries.php
common/code/boost_library.php
common/code/test/tests/libraries.phpt
development/library_metadata.html
doc/libraries.php

- Removed 'std', 'std-proposal', 'std-tr1' throughout the codes
- Titlize 'C++ standard minimum level' in the doc page

Remove all std references

---

common/code/boost_utility.php
style-v2/css_0/content.css

- Put libs with missing cxxstd values after the ones with values
- Increase the width of 'C++ Standard Minimum Level' label

Update 'C++ Minimum' sort

---

feed/history/boost_1_75_0.qbk

This PR addresses @jwakely request in https://github.com/boostorg/geometry/issues/590#issuecomment-766786462
-----
Please, if any needed, feel free to make any English language corrections to this notice.

Add C++14 requirement notice to release notes of 1.75

---

community/reviews.html

Remove broken link to Google+ community

---

community/committee.html
community/counted_body.html
community/cpp.html
community/error_handling.html
community/exception_safety.html
community/feature_model_diagrams.html
community/generic_programming.html
community/groups.html
community/gsoc.html
community/gsoc_2006_boost_overview.html
community/imc_summer_of_code_2016.html
community/implementation_variations.html
community/index.html
community/irc.html
community/official_library_maintainer_program.html
community/policy.html
community/requests.html
community/review_schedule.html
community/reviews.html
donate/index.html

Grammar corrections in 20 files in community folder with 196 additions and 204 deletions.

Grammar corrections in community folder

---

common/code/boost_config.php
development/website_updating.html

Hi,
A few months back, when setting up a test copy of the boost website, I made some notes which might help clarify the documentation.

website doc

---

feed/history/boost_1_76_0.qbk

I _think_ I've got the quickbook right ...

Outcome changes

---

feed/history/boost_1_76_0.qbk

Update release notes for JSON

---

feed/history/boost_1_76_0.qbk

Alphabetize and tidy JSON notes

---

feed/history/boost_1_77_0.qbk

fix uuid 1.77 relnotes pr link - missing underscore

---

community/policy.html
development/website_updating.html

Few minor cleanups, nothing major.
I did not want to get into the trouble for recommending specific browsers so I just suggested 2 modern browsers.

Modernize text in policy.html and website_updating.html 

---

feed/history/boost_1_77_0.qbk
feed/history/boost_1_78_0.qbk
feed/history/boost_1_79_0.qbk

This is for 1.79 and the past 2 releases where I seemingly forgot about this.
A quick check if the added notes make sense and read well to native speakers would be appreciated

Add Nowide release notes

---

feed/history/boost_1_80_0.qbk

Update Wave changes for 1.80

---

feed/history/boost_1_81_0.qbk

DLL, LexicalCast, Stacktrace, PFR and Variant changes for 1.81

DLL, LexicalCast, Stacktrace, PFR and Variant

---

development/requirements.html

Based on https://lists.boost.org/Archives/boost/2023/02/254025.php

Add library requirement of latest C++ standard support

---

feed/history/boost_1_82_0.qbk

cc: @jzmaddock, @NAThompson, @ckormanyos

Add release notes for math, multiprecision, and test

---

feed/history/boost_1_82_0.qbk

Beast release note 1.82

---

common/heading.html
doc/libs/1_78_0/libs/utility/doc/html/utility/utilities/operators.html
users/index.html

Fix bad links

---

community/reviews.html
development/submissions.html

Follow-up to my recent blunder
https://lists.boost.org/Archives/boost/2023/05/254708.php

Add notice to Review Manager about avoiding conflict of interest

---

feed/history/boost_1_83_0.qbk
patches/1_83_0/0001-unordered-fix-copy-assign.patch
patches/index.html

This PR adds a patch required to fix https://github.com/boostorg/unordered/issues/205

Add Unordered patch for 1.83.0

---

feed/history/boost_1_83_0.qbk

Fixed link to patch file for https://github.com/boostorg/unordered/issues/205

fixed link to patch file

---

feed/history/boost_1_83_0.qbk

This will show up on the asociated blurbs on boost.org. Fixes #785.

added new and updated libs summary for Boost 1.83

---

feed/history/boost_1_84_0.qbk

This will show up on the asociated blurbs on boost.org.

added new and updated libs summary for Boost 1.84

---

generated/download-items.html
generated/home-items.html
users/history/version_1_84_0.html

Reverts boostorg/website#808
JFrog is down again.

Revert "Set downloads to use jfrog"

---

generated/download-items.html
generated/home-items.html
users/history/version_1_84_0.html

Reverts boostorg/website#810
JFrog is back. :-)

Revert "Revert "Set downloads to use jfrog""

---

common/menu-community.html
donate/index.html

Also update the link to Boost Foundation as the older link is no longer valid.

Update references to Steering Committee to Boost Foundation

---

feed/history/boost_1_85_0.qbk

release notes MSM

---

feed/history/boost_1_85_0.qbk

The change is in the beta. Just forgot to mention the change in changelog

Add info on stacktrace docs change

---

feed/history/boost_1_85_0.qbk

CC: @jzmaddock, @ckormanyos, @NAThompson

1.85 Release notes for: math, multiprecision, random, odeint, and test

---

feed/history/boost_1_86_0.qbk

CC: @ckormanyos, @jzmaddock, @NAThompson

1.86 Release notes for charconv, math, multiprecision, ODEint, and test

---

community/review_schedule.html

Please, @klemens-morgenstern, if you could provide the missing GitHub links and MQTT submitter, thanks.

Schedule reviews of MQTT and SQLite

---

community/review_schedule.html

@mloskot as requested in your email. Please let me know if any changes are needed.
CC: @ckormanyos and @jzmaddock

Add decimal to review schedule

---

community/review_schedule.html

@mloskot for your review. I didn't see any objections to the timing on the list.
CC: @pdimov, @cmazakas

Add hash2 to review schedule

---

feed/history/boost_1_87_0.qbk

release docs for cobalt & process.

  release notes for cobalt & process.

---

community/review_schedule.html

I left SQLite in the pending column in case that one needs to be redone.

Cleanup Review Schedule Page

---

generated/home-items.html

filled in 1.88 blurb

---

community/review_schedule.html

@joaquintides and @Becheler could you please double check this information? Once I get confirmation I'll merge it in. Thanks.

Add Bloom to the review schedule
